### ISSUE TITLE
climada.test.test_gdp_asset_integr.TestGDP2AssetClassCountries.test_wrong_iso3_fail

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#210]
Unknown country ISO: OYY
```txt
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/climada_ci_night/workspace/climada/util/coordinates.py", line 1070, in country_iso2natid
    natids.append(ISIMIP_NATID_TO_ISO.index(iso))
ValueError: 'OYY' is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/climada_ci_night/workspace/climada/test/test_gdp_asset_integr.py", line 32, in test_wrong_iso3_fail
    testGDP2A.set_countries(countries=['OYY'], path=DEMO_GDP2ASSET)
  File "/var/lib/jenkins/jobs/climada_ci_night/workspace/climada/entity/exposures/gdp_asset.py", line 75, in set_countries
    gdp2a_list.append(self._set_one_country(countries[cntr_ind],
  File "/var/lib/jenkins/jobs/climada_ci_night/workspace/climada/entity/exposures/gdp_asset.py", line 117, in _set_one_country
    natID = u_coord.country_iso2natid(countryISO)
  File "/var/lib/jenkins/jobs/climada_ci_night/workspace/climada/util/coordinates.py", line 1072, in country_iso2natid
    raise LookupError(f'Unknown country ISO: {iso}') from ver
LookupError: Unknown country ISO: OYY
```

**Comment by emanuel-schmid** [comment]
🎉 😃
