### ISSUE TITLE
Crop Potential test file fails to be read under Windows

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#23]
When running under Windows there seems to be a problem between rasterio and the demo file used in the test:

```
======================================================================
ERROR: test_load_EU_all (climada.hazard.test.test_crop_potential.TestCropPotential)
Test defining crop potential hazard from complete demo file (Central Europe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rasterio\_base.pyx", line 213, in rasterio._base.DatasetBase.__init__
  File "rasterio\_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio\_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: 'data\demo\lpjml_ipsl-cm5a-lr_ewembi_historical_2005soc_co2_yield-whe-noirr_annual_FR_DE_DEMO_1861_2005.nc' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "climada\hazard\test\test_crop_potential.py", line 38, in test_load_EU_all
    soc='2005soc', co2='co2', crop='whe', irr='noirr', fn_str_var=FN_STR_DEMO)
  File "climada\hazard\crop_potential.py", line 185, in set_from_single_run
    geometry=list([shapely.geometry.box(bbox[0], bbox[1], bbox[2], bbox[3])]))
  File "climada\hazard\base.py", line 253, in set_raster
    geometry, dst_crs, transform, width, height, resampling))
  File "climada\hazard\centroids\centr.py", line 218, in set_raster_file
    height, resampling)
  File "climada\util\coordinates.py", line 456, in read_raster
    with rasterio.open(file_name, 'r') as src:
  File "C:\...\Anaconda3\envs\env_climada\lib\site-packages\rasterio\env.py", line 423, in wrapper
    return f(*args, **kwds)
  File "C:\...\Anaconda3\envs\env_climada\lib\site-packages\rasterio\__init__.py", line 216, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio\_base.pyx", line 215, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: 'data\demo\lpjml_ipsl-cm5a-lr_ewembi_historical_2005soc_co2_yield-whe-noirr_annual_FR_DE_DEMO_1861_2005.nc' not recognized as a supported file format.
```

**Comment by emanuel-schmid** [comment]
The file itself can be read though with netCDF4.Dateset()
```
>>> import netCDF4 as nc
>>> nc.Dataset('data/demo/lpjml_ipsl-cm5a-lr_ewembi_historical_2005soc_co2_yield-whe-noirr_annual_FR_DE_DEMO_1861_2005.nc')
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    CDI: Climate Data Interface version 1.9.8 (https://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    history: Wed Apr 22 10:58:30 2020: cdo -k grid sellonlatbox,-5,16,42,55 /Users/eberenzs/polybox/Shared/ISIMIP_Droughts/01_Data/ISIMIP_2b/Historical/lpjml_ipsl-cm5a-lr_ewembi_historical_2005soc_co2_yield-whe-noirr_global_annual_1861_2005.nc /Users/eberenzs/polybox/Shared/ISIMIP_Droughts/01_Data/ISIMIP_2b/Historical/lpjml_ipsl-cm5a-lr_ewembi_historical_2005soc_co2_yield-whe-noirr_FR_DE_annual_1861_2005.nc
    institution: Potsdam Institute for Climate Impact Research
    title: LPJmL simulations for ISIMIP2b
    contact: Christoph Mueller <cmueller@pik-potsdam.de>
    comment3: constant current management, all crops everywhere, GGCMI harmnon growing seasons
    isimip_round: ISIMIP2b
    isimip_upload_date: May  5
    isimip_upload_version: 2
    isimip_qc_version: 1
    isimip_test_suite_pass_date: 2017.07.07
    project: isimip2b
    product: output
    dataset_type: Impact model output
    bias_correction: EWEMBI
    world_region: Global land
    sector: Agriculture
    impact_model: LPJmL
    model: ipsl-cm5a-lr
    experiment: historical
    period: historical
    ensemble: r1i1p1
    time_frequency: yr
    country: ALL
    social_forcing: 2005soc
    co2_forcing: co2
    irrigation_forcing: no irrigation (noirr)
    crop_id: whe
    crop: Wheat
    publisher: ISIMIP coordination team <info@isimip.org>
    description: LPJmL model output prepared according to the ISIMIP2b simulation protocol (https://www.isimip.org/protocol/#isimip2b). Model details: https://www.isimip.org/impactmodels/details/83/. Published under CC BY 4.0 licence. Use of these data strictly according to the ISIMIP Terms of Use (https://www.isimip.org/protocol/terms-of-use/). These data may change! Keep up-to-date on corrections & caveats: https://www.isimip.org/outputdata/#output-data-changelog
    doi: NA
    licence: CC BY 4.0
    creator: Christoph Müller <cmueller@pik-potsdam.de>
    tracking_id: 41942b84-01fd-4795-94a1-8a49ec09589d
    creation_date: 2018-11-13T13:55:13Z
    CDO: Climate Data Operators version 1.9.8 (https://mpimet.mpg.de/cdo)
    dimensions(sizes): time(145), lon(42), lat(26)
    variables(dimensions): float64 time(time), float64 lon(lon), float64 lat(lat), float32 yield(time,lat,lon)
    groups:
```

**Comment by sameberenz** [comment]
is this still an issue?
It works fine under UNIX.
Do you get the same issue with [(test_cropyield_isimip)](https://github.com/CLIMADA-project/climada_python/blob/develop/climada/entity/exposures/test/test_cropyield_isimip.py)? (loading a similiarly created NetCDF-file)

**Comment by sameberenz** [comment]
Since I don't work on Windows, I would appreciate if someone with CLIMADA running on a Windows-machine could possibly solve this issue. Thank you!
