### ISSUE TITLE
Unit Test Failure climada.engine.uncertainty_quantification.test.test_uncertainty.TestOutput.test_plot_unc_imp

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#323]
**Error Message**: `operands could not be broadcast together with shapes (5,0) (0,5)`

**Stacktrace**
```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/climada_branches/branches/develop/workspace/climada/engine/uncertainty_quantification/test/test_uncertainty.py", line 266, in test_plot_unc_imp
    plt_sens_2 = unc_output.plot_sensitivity_second_order(salib_si='S1')
  File "/var/lib/jenkins/jobs/climada_branches/branches/develop/workspace/climada/engine/uncertainty_quantification/unc_output.py", line 862, in plot_sensitivity_second_order
    s2_conf_matrix = s2_conf_matrix + s2_conf_matrix.T - \
ValueError: operands could not be broadcast together with shapes (5,0) (0,5) 
```

Strangely the error did occur first on the ci_night jenkins project and was not triggered by a particular commit. Dpendency issue?

**Comment by chahank** [comment]
This is a new error. I will look into it.

**Comment by chahank** [comment]
The issue seems to be related to the change in the demo file 'test_unc_output_impact' on the API which is missing the sensitivity data. I will create a new demo file to fix this issue.
