### ISSUE TITLE
cfgrib 0.9.10 and grib files from https://opendata.dwd.de

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#360]
There seems to be an incompatibility of cfgrib 0.9.10 when reading (archived?) icongrib files from https://opendata.dwd.de.

Test fails like this:

```
 climada.hazard.test.test_storm_europe.TestReader.test_icon_read
 Error Details

'PosixPath' object is not iterable

 Stack Trace

Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/climada_branches/branches/PR-358/workspace/climada/hazard/test/test_storm_europe.py", line 200, in test_icon_read
    haz = StormEurope.from_icon_grib(
  File "/var/lib/jenkins/jobs/climada_branches/branches/PR-358/workspace/climada/hazard/storm_europe.py", line 442, in from_icon_grib
    ds_i = xr.open_dataset(gripfile_path_i, engine='cfgrib')
  File "/var/lib/jenkins/.conda/envs/climada_env/lib/python3.8/site-packages/xarray/backends/api.py", line 495, in open_dataset
    backend_ds = backend.open_dataset(
  File "/var/lib/jenkins/.conda/envs/climada_env/lib/python3.8/site-packages/cfgrib/xarray_plugin.py", line 99, in open_dataset
    store = CfGribDataStore(
  File "/var/lib/jenkins/.conda/envs/climada_env/lib/python3.8/site-packages/cfgrib/xarray_plugin.py", line 39, in __init__
    self.ds = opener(filename, **backend_kwargs)
  File "/var/lib/jenkins/.conda/envs/climada_env/lib/python3.8/site-packages/cfgrib/dataset.py", line 728, in open_fieldset
    index = messages.FieldsetIndex.from_fieldset(fieldset, index_keys, computed_keys)
  File "/var/lib/jenkins/.conda/envs/climada_env/lib/python3.8/site-packages/cfgrib/messages.py", line 365, in from_fieldset
    iteritems = enumerate(fieldset)
TypeError: 'PosixPath' object is not iterable
```

**Comment by luseverin** [comment]
I do not see any test from `test_storm_europe` or `test_hazard` failing when updating to `cfgrib=0.9.10.3`. Is this issue still ongoing?

**Comment by luseverin** [comment]
Actually I also do not see any problem when I upgrade to `cfgrib>=0.9.14`.
