### ISSUE TITLE
Installation failed for climada, issue with library `fiona`

### ISSUE THREAD

**Issue by manniepmkam** [CLIMADA-project/climada_python#470]
I'm trying to reinstall the climada on my machine following the [installation guide](https://climada-python.readthedocs.io/en/stable/guide/Guide_Installation.html). However, it fails the installation test with given errors:

```
python -m unittest climada.engine.test.test_impact climada.engine.test.test_cost_benefit 

Traceback (most recent call last):
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/kampu/Documents/git_repoositories/climada/climada_python/climada/__init__.py", line 25, in <module>
    from .util.constants import *
  File "/Users/kampu/Documents/git_repoositories/climada/climada_python/climada/util/__init__.py", line 25, in <module>
    from .constants import *
  File "/Users/kampu/Documents/git_repoositories/climada/climada_python/climada/util/constants.py", line 47, in <module>
    from fiona.crs import from_epsg
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/__init__.py", line 85, in <module>
    with fiona._loading.add_gdal_dll_directories():
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)
```

**Comment by manniepmkam** [comment]
I am following the comments from #454, but it's fails when I gave the command
```
conda activate
conda create -c conda-forge -n gdal-test python=3.8 gdal=3.4.0 fiona=1.8.20
conda activate climada
python -c 'import fiona; print(fiona.__file__)'
```
Which it gives error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Symbol not found: _ZSTD_compressBound
  Referenced from: /Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/../../../libgdal.30.dylib
  Expected in: /Users/kampu/opt/anaconda3/envs/climada_env/lib/libblosc.1.dylib
 in /Users/kampu/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/../../../libgdal.30.dylib
```

**Comment by emanuel-schmid** [comment]
thanks! you can remove the gdal-test environment, that was just for checking out things.
```
conda deactivate
conda env remove -n gdal-test
```

**Comment by emanuel-schmid** [comment]
But can you let me know what is your fiona version:
```
conda activate climada_env
conda list fiona
```

**Comment by manniepmkam** [comment]
Here are the versions:

```
# packages in environment at /Users/kampu/opt/anaconda3/envs/climada_env:
#
# Name                    Version                   Build  Channel
fiona                     1.8.20           py38h2077077_4    conda-forge
# packages in environment at /Users/kampu/opt/anaconda3/envs/climada_env:
#
# Name                    Version                   Build  Channel
gdal                      3.4.0           py38hf509309_12    conda-forge
libgdal                   3.4.0               h3ab75b0_12    conda-forge
```

**Comment by emanuel-schmid** [comment]
Thanks! That's exactly what I have, so it should be fine - in theory.
What is the output of 
```bash
conda deactivate && conda deactivate && conda deactivate && conda activate && conda list gdal && conda list fiona
```

**Comment by manniepmkam** [comment]
it gives this
```
(climada_env) kampu@wcr-mac-22 requirements % conda deactivate && conda deactivate && conda deactivate && conda activate && conda list gdal && conda list fiona
# packages in environment at /Users/kampu/opt/anaconda3:
#
# Name                    Version                   Build  Channel
# packages in environment at /Users/kampu/opt/anaconda3:
#
# Name                    Version                   Build  Channel
```

> Thanks! That's exactly what I have, so it should be fine - in theory. What is the output of
> 
> ```shell
> conda deactivate && conda deactivate && conda deactivate && conda activate && conda list gdal && conda list fiona
> ```

**Comment by manniepmkam** [comment]
> What is the output of
> 
> ```shell
> conda env list
> ```

```
(base) kampu@wcr-mac-22 requirements % conda env list
# conda environments:
#
base                  *  /Users/kampu/opt/anaconda3
climada_env              /Users/kampu/opt/anaconda3/envs/climada_env
```

**Comment by emanuel-schmid** [comment]
What error messages do you get when you run the following?
```bash
conda env update -n climada_env -f /Users/kampu/Documents/git_repoositories/climada/climada_python/requirements/env_climada.yml
python -c 'import fiona'
```

**Comment by manniepmkam** [comment]
The problem is solved by removing anaconda completely and reinstall anaconda and climada afterwards.
