### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by GEMSS3D** [CLIMADA-project/climada_python#511]
Hi,

I installed Climada using step by step approach using anaconda. When I tried to run the test script, I get error message as "SSL: CERTFIFCATE_VERIFY_FAILED"

Can you please help me as what I am doing wrong here? I used the previous version in Matlab.  I need to use this as soon as possible. Any help is greatly appreciated.

Thanks
Venkat

![image](https://user-images.githubusercontent.com/22398147/177628822-9ee59ac3-560e-4ce5-b960-81b5635e6e4d.png)

I am sharing the error message here

Traceback (most recent call last):
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\climada\engine\test\test_impact.py", line 44, in <module>
    HAZ_TEST_MAT = get_haz_test_file('atl_prob_no_name')
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\climada\engine\test\test_impact.py", line 39, in get_haz_test_file
    test_ds = client.get_dataset_info(name=ds_name, status='test_dataset')
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\climada\util\api_client.py", line 306, in get_dataset_info
    jarr = self.list_dataset_infos(data_type=data_type, name=name, version=version,
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\climada\util\api_client.py", line 270, in list_dataset_infos
    datasets = [DatasetInfo.from_json(ds) for ds in Client._request_200(url, params=params)]
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\climada\util\api_client.py", line 206, in _request_200
    page = requests.get(url, **kwargs)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\venkat.kolluru\Anaconda3\envs\climada_env\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='climada.ethz.ch', port=443): Max retries exceeded with url: /data-api/v1/dataset?name=atl_prob_no_name&status=test_dataset&limit=100000 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

**Comment by chahank** [comment]
I do not know this error. @emanuel-schmid : do you have an idea what is the issue?

**Comment by emanuel-schmid** [comment]
@GEMSS3D - thanks for the inquiry. Don't know yet what's wrong. Are you connecting through a proxy maybe?

**Comment by GEMSS3D** [comment]
Hi,
Thanks for your feedback. I am not sure as to what you mean by proxy. I exactly followed the step by step approach after creating climada_env. I tried to install on my personal laptop. It doesn't work there either. I am not sure as what could be the problem. I am using latest version of anaconda.  Any suggestions as how to install on windows 10 will be very useful for me. Thanks. Venkat

**Comment by emanuel-schmid** [comment]
Oh? Many thanks for the solution! Good to know.
To be honest - I don't really understand how this solved the problem. But as long as it did, that's probably fine. (;
Best, Emanuel
