### ISSUE TITLE
tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5 from the data api seems to be corrupt

### ISSUE THREAD

**Issue by LennardB94** [CLIMADA-project/climada_python#605]
Dear all,

It seems to me that the file tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5
provided by the data api is corrupt.

Code example to reproduce the error:
```

import climada
import climada.util.coordinates as u_coord
import numpy as np
from climada.entity.impact_funcs import ImpactFuncSet, ImpfTropCyclone
from climada.hazard import Centroids
from climada.util.api_client import Client
client = Client()

# this works
properties = {"res_arcsec": "150",
              "climate_scenario": "rcp60",
              "nb_synth_tracks": "10",
              "spatial_coverage": "global",
              "ref_year": "2080"}

tc = client.get_hazard("tropical_cyclone",
                       properties=properties)

# this fails with error msg

properties = {"res_arcsec": "150",
              "climate_scenario": "rcp85",
              "nb_synth_tracks": "10",
              "spatial_coverage": "global",
              "ref_year": "2080"}

tc = client.get_hazard("tropical_cyclone",
                       properties=properties)

```
which provides me the output
```

2022-12-14 16:02:52,061 - climada.util.api_client - WARNING - Download failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!, retrying...
2022-12-14 16:02:54,076 - climada.util.api_client - WARNING - Download failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!, retrying...
2022-12-14 16:02:57,084 - climada.util.api_client - WARNING - Download failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!, retrying...
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"
climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"
climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"
climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\climada-api-3\minimal_example.py", line 15, in <module>
    tc = client.get_hazard("tropical_cyclone",
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 583, in get_hazard
    return self.to_hazard(dataset, dump_dir)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 607, in to_hazard
    hazard_list = [
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 608, in <listcomp>
    Hazard.from_hdf5(self._download_file(target_dir, dsf))
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 473, in _download_file
    return self._download_file(local_path=local_path, fileinfo=fileinfo, check=check,
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\cTraceback (most recent call last):
  File "C:\Users\\climada-api-3\minimal_example.py", line 16, in <module>    
    tc = client.get_hazard("tropical_cyclone",                                              File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 581, in get_hazard                                     dataset = self.get_dataset_info(data_type=hazard_type, name=name, version=version,      File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 312, in get_dataset_info                                     raise Client.NoResult("there is no dataset meeting the requirements")                 climada.util.api_client.Client.NoResult: there is no dataset meeting the requirements     PS C:\Users\\climada-api-3> python .\minimal_example.py
2022-12-14 16:10:22,868 - climada.util.api_client - WARNING - Download failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!, retrying...
2022-12-14 16:10:24,881 - climada.util.api_client - WARNING - Download failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!, retrying...
2022-12-14 16:10:27,891 - climada.util.api_client - WARNING - Download failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!, retrying...
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"      
climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"      
climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"      
climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\climada-api-3\minimal_example.py", line 27, in <module>    
    Hazard.from_hdf5(self._download_file(target_dir, dsf))
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 473, in _download_file
    return self._download_file(local_path=local_path, fileinfo=fileinfo, check=check,
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 473, in _download_file
    return self._download_file(local_path=local_path, fileinfo=fileinfo, check=check,
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 473, in _download_file
    return self._download_file(local_path=local_path, fileinfo=fileinfo, check=check,  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 470, in _download_file
    raise dle  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\climada\util\api_client.py", line 459, in _download_file
    raise Download.Failed("Download seems to be in progress, please try again later"climada.util.api_client.Download.Failed: Download seems to be in progress, please try again later or remove cache entry by calling `purge_cache(Path('C:\Users\\climada\data\hazard\tropical_cyclone\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\v2\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

```

Consulting the data-api, I find
![image](https://user-images.githubusercontent.com/98521113/207634989-2aab130b-cac9-4503-b86c-5e53727de91b.png)
, with a filesize of 934MB, whereas
![image](https://user-images.githubusercontent.com/98521113/207635379-17bc162c-d681-4212-b7ec-b8683e12ef8b.png)
has a filesize of 2.2GB, and I would expect the both files to be similar in size. Moreover, the checksum of the file seems to be invalid.

Best,
Lennard

**Comment by emanuel-schmid** [comment]
Hi Lennard. Thanks for submitting. I'm checking ...

**Comment by emanuel-schmid** [comment]
Hi Lennard. Thanks for submitting this.

The data set seems to be alright, also the file size is as expected. What caused this is an incident that happened when you used the client to download the very same data set in the past and caused the download to somehow be interrupted.

This led to a corrupt file in your local filesystem. Now when you try again to download it, the client thinks a download is already running and does not want to interfere. The remedy is listed in the error message - probably too fart to the right and too many times so it may be considered as irrelevant noise:

climada.util.api_client.Download.Failed: 
Download seems to be in progress, please try again later or remove cache entry by calling
 `purge_cache(Path('C:\\Users\\climada\\data\\hazard\\tropical_cyclone\\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080\\v2\\tropical_cyclone_10synth_tracks_150arcsec_rcp85_global_2080.hdf5'))`!

The command is to be called in the same notebook, script or shell where you use the client.

You can also just delete that file manually. Should work too. 😁

**Comment by LennardB94** [comment]
Purging does indeed do the trick. Why is it expected that the file size of the hdf5 file for the rcp85 scenario is approximately half the size of the rcp60 scenario?

**Comment by emanuel-schmid** [comment]
🤔 that is a very good question. (i.o.w. I have no clue) 

Looking for experts ...

**Comment by zeliest** [comment]
thank you for pointing out the size differences, there is indeed an error in the files for RCP8.5 which were uploaded later on, they should be the same size. This is being corrected.

**Comment by zeliest** [comment]
The method to consider climate change scenarios to create these datasets is based on a change in frequency and intensity as calculated by the publication Knutsen at al. (2015), which considers RCP4.5 until the end of the century. RCPs which exceed the emission levels reached by this RCP may not be suitable to use with this method, so we will not be providing RCP8.5 for now.

**Comment by emanuel-schmid** [comment]
all datasets tropical_cyclone, climate_scanario rcp85 have been discarded
