### ISSUE TITLE
upgrade cartopy 0.20 -> 0.21

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#693]
Since the update to cartopy 0.21, the unit test `climada.test.test_plot.TestPlotter.test_exposures_value_pass` fails gracelessly on Jenkins because it runs out of memory:

```log
======================================================================
ERROR [31.423s]: test_exposures_value_pass (climada.test.test_plot.TestPlotter)
Plot exposures values.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/climada_branches/branches/develop/workspace/climada/test/test_plot.py", line 123, in test_exposures_value_pass

  ...

  File "/home/IEDAdmin/miniconda3/envs/climada_env/lib/python3.9/site-packages/pyproj/utils.py", line 129, in _copytobuffer
    return xxx.astype("d", order="C", copy=not inplace), DataType.ARRAY
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 981. MiB for an array with shape (128544732,) and data type float64
```

(On Windows, the test consumes, unrestricted, about 10G.)

**Comment by emanuel-schmid** [comment]
we need a more considerate test - or a smarter plot. 🤷

**Comment by emanuel-schmid** [comment]
first encountered after dependency upgrade (#682)

**Comment by NicolasColombi** [comment]
Hi @emanuel-schmid, the problem should be fixed, the issue was with `plot.raster()` I simply applied a coarser resolution and now it takes around 400Mb of RAM to execute the test. See PR #

**Comment by peanutfun** [comment]
Upgraded with #682
