### ISSUE TITLE
Litpop.from_shape_and_countries does not handle GeoSeries as a shape definition (patch proposed)

### ISSUE THREAD

**Issue by IanHopkinson** [CLIMADA-project/climada_python#826]
I had an issue with `LitPop.from_shape_and_countries` whereby it would not accept `geopandas.geoseries.GeoSeries`

The error message was:

> 2023-12-12 10:32:01,162 - climada.entity.exposures.litpop.gpw_population - WARNING - Reference year: 2018. Using nearest available year for GPW data: 2020
> Traceback (most recent call last):
>   File "C:\Users\ianho\code\2023\hdx-scraper-climada\src\hdx_scraper_climada\create_csv_files.py", line 204, in <module>
>     export_litpop_data_to_csv(country="Haiti")
>   File "C:\Users\ianho\code\2023\hdx-scraper-climada\src\hdx_scraper_climada\create_csv_files.py", line 109, in export_litpop_data_to_csv
>     admin1_litpop = LitPop.from_shape_and_countries(admin1_shape, country_iso3a, res_arcsec=150)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\ianho\code\2023\hdx-scraper-climada\venv\Lib\site-packages\climada\entity\exposures\litpop\litpop.py", line 424, in from_shape_and_countries
>     gdf = gdf.append(exp.gdf.loc[exp.gdf.geometry.within(shp)])
>           ^^^^^^^^^^
>   File "C:\Users\ianho\code\2023\hdx-scraper-climada\venv\Lib\site-packages\pandas\core\generic.py", line 6204, in __getattr__
>     return object.__getattribute__(self, name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'GeoDataFrame' object has no attribute 'append'. Did you mean: '_append'?

I fixed the issue for me by patching this line:
```gdf = gdf.append(exp.gdf.loc[exp.gdf.geometry.within(shp)])```
to
```gdf = gdf._append(exp.gdf.loc[exp.gdf.geometry.within(shp)])```
changing .append to ._append:

https://github.com/CLIMADA-project/climada_python/blob/e41222210bfb99e92829c0a86f1db2f31355abf5/climada/entity/exposures/litpop/litpop.py#L424

My code now runs and gives the expected output but raises this warning:

> C:\Users\ianho\code\2023\hdx-scraper-climada\venv\Lib\site-packages\climada\entity\exposures\litpop\litpop.py:424: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
>   gdf = gdf._append(exp.gdf.loc[exp.gdf.geometry.within(shp)])
>

**Comment by peanutfun** [comment]
@IanHopkinson Thank you forthe bug report. We must have missed that in our testing. `pandas` has removed `append` in favor of `concat`. `_append` is a private method that should not be used. Looking at the implementation, we could actually improve it a lot, because we only subselect the existing GeoDataFrame. Appending or concatenating should not be necessary.
