### ISSUE TITLE
Fiona error . The EPSG code is unknown no such table: metadata

### ISSUE THREAD

**Issue by devsun077** [CLIMADA-project/climada_python#926]
**Describe the bug**
I am following simple instruction to install dependancy in mamba environment. I am hit up error when I execute single test
```
python -m unittest climada.engine.test.test_impact
```

ERROR:
```
ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
Traceback (most recent call last):
  File "fiona\crs.pyx", line 585, in fiona.crs.CRS.from_epsg
  File "fiona\_err.pyx", line 265, in fiona._err.exc_wrap_int
fiona._err.CPLE_AppDefinedError: PROJ: proj_create_from_database: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\main.py", line 101, in __init__
    self.parseArgs(argv)
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\main.py", line 150, in parseArgs
    self.createTests()
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\main.py", line 161, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\loader.py", line 232, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\loader.py", line 232, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\miniforge3\envs\climada_env\Lib\unittest\loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Githubs\climada_python\climada\__init__.py", line 24, in <module>
    from .util.config import CONFIG
  File "E:\Githubs\climada_python\climada\util\__init__.py", line 25, in <module>
    from .constants import *
  File "E:\Githubs\climada_python\climada\util\constants.py", line 205, in <module>
    DEF_CRS_FIONA = from_epsg(DEF_EPSG)
                    ^^^^^^^^^^^^^^^^^^^
  File "fiona\crs.pyx", line 1265, in fiona.crs.from_epsg
  File "fiona\crs.pyx", line 589, in fiona.crs.CRS.from_epsg
fiona.errors.CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
```

**Expected behavior**

**Screenshots**

**Climada Version:** [Version or branch]

**System Information (please complete the following information):**
 - Operating system and version: [e.g. Ubuntu 22.04, macOS 14.3.1, Windows 10]
 - Python version: [e.g. 3.10] 
 (to obtain this information execute > import sys  >print(sys.version))

**Additional context**

**Comment by peanutfun** [comment]
@devsun077 Thanks for reporting. We encountered this type of issue before. It is not related to Climada but results from an incompatibility within the dependencies. The error occurs when Fiona is not able to read the PROJ database.

The issue likely originates from a problem during installation. You claim that you followed the simple installation instructions, but the backtrace shows the Climada source code placed in `E:\Githubs\climada_python`. Checking out the source code is not part of the simple installation instructions.

I suggest you remove your current `climada_env`, follow the installation instructions precisely, and then report back if the problem persists. Also, make sure you execute the unittest with the environment activated.

**Comment by peanutfun** [comment]
Closing due to inactivity. @devsun077, please report back if the problem persists.
