### ISSUE TITLE
Error when running the code to verify installation

### ISSUE THREAD

**Issue by salmiah-ls** [CLIMADA-project/climada_python#943]
I installed Climada on Windows 10, Miniforge3, Python 3.11.9 by following instruction in this [page](https://climada-python.readthedocs.io/en/stable/guide/install.html)

Step 1 and 2 run well, but when I run the code in step 3

`(climada_env) C:\Users\Salmiah>python -m unittest climada.engine.test.test_impact`

it returns error like below:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\main.py", line 101, in __init__
    self.parseArgs(argv)
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\main.py", line 150, in parseArgs
    self.createTests()
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\main.py", line 161, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\loader.py", line 232, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\loader.py", line 232, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\unittest\loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\climada\__init__.py", line 24, in <module>
    from .util.config import CONFIG
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\climada\util\__init__.py", line 26, in <module>
    from .coordinates import *
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\climada\util\coordinates.py", line 33, in <module>
    import dask.dataframe as dd
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\__init__.py", line 98, in <module>
    from dask.dataframe import backends, dispatch, rolling
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\backends.py", line 15, in <module>
    from dask.dataframe.core import DataFrame, Index, Scalar, Series, _Frame
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\core.py", line 36, in <module>
    from dask.dataframe import methods
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\methods.py", line 34, in <module>
    from dask.dataframe.utils import is_dataframe_like, is_index_like, is_series_like
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\utils.py", line 20, in <module>
    from dask.dataframe import (  # noqa: F401 register pandas extension types
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\_dtypes.py", line 9, in <module>
    from dask.dataframe.extensions import make_array_nonempty, make_scalar
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\extensions.py", line 8, in <module>
    from dask.dataframe.accessor import (
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\accessor.py", line 126, in <module>
    class DatetimeAccessor(Accessor):
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\accessor.py", line 81, in __init_subclass__
    _bind_property(cls, pd_cls, attr, min_version)
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\dataframe\accessor.py", line 35, in _bind_property
    setattr(cls, attr, property(derived_from(pd_cls, version=min_version)(func)))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\utils.py", line 981, in wrapper
    method.__doc__ = _derived_from(
                     ^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\utils.py", line 934, in _derived_from
    method_args = get_named_args(method)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\site-packages\dask\utils.py", line 695, in get_named_args
    s = inspect.signature(func)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\inspect.py", line 3263, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\inspect.py", line 3011, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\inspect.py", line 2599, in _signature_from_callable
    call = _descriptor_get(call, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Salmiah\miniforge3\envs\climada_env\Lib\inspect.py", line 2432, in _descriptor_get
    return get(descriptor, obj, type(obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor '__call__' for 'type' objects doesn't apply to a 'property' object
```

Did I miss any step? Or any step that I did not execute properly?

Thanks

**Comment by spjuhel** [comment]
Probably related to: https://github.com/dask/dask/issues/11038

I would either try to downgrade to python 3.9.10, or update dask to 2024.4.1 (But if it did not by default it is probably incompatible with the current dependencies of Climada)

**Comment by salmiah-ls** [comment]
I installed on macOS Ventura 13.4.1, Python 3.11.6, and Miniforge3 also, it returns status OK at the end even though there are many warnings before.

**Comment by salmiah-ls** [comment]
I re-install in my Windows 10 but with Advanced Instructions (Python 3.9), and it returns OK as well.
